# Imagen base de PostgreSQL 15.17 sobre Alpine 3.22
FROM postgres:15.17-alpine3.22

# Variables de entorno para la base de datos
ENV POSTGRES_USER=fintech_user
ENV POSTGRES_PASSWORD=fintech_pass123
ENV POSTGRES_DB=fintech_db

# Puerto expuesto por defecto de PostgreSQL
EXPOSE 5432