
# ---- ETAPA 1: Contruir ----
# Imagen base: usamos Node.js versión 18 (ligera con Alpine Linux)
# Se usa el alias “build” para diferenciar la etapa en la construcción del front, ya que esta se hace en 2 etapas.
FROM node:18-alpine AS build

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos primero los archivos de dependencias
COPY package.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código fuente
COPY . .

# Generamos los archivos estáticos listos para producción (carpeta /build)
RUN npm run build


# ---- ETAPA 2: Servir ----
# Usamos Nginx para servir los archivos estáticos generados
FROM nginx:alpine

# Copiamos los archivos del build al directorio que sirve Nginx (“Primera etapa”)
COPY --from=build /app/build /usr/share/nginx/html

# Exponemos el puerto 80 (puerto por defecto de Nginx)
EXPOSE 80

# Nginx arranca automáticamente al iniciar el contenedor
CMD ["nginx", "-g", "daemon off;"]
